### ISSUE TITLE
Do you accept "soft CPUs"?

### ISSUE THREAD

**Issue by mithro** [larsbrinkhoff/awesome-cpus#27]
Hi!

I was wondering if you accept soft-cpus like the [LatticeMico32](http://www.latticesemi.com/en/Products/DesignSoftwareAndIP/IntellectualProperty/IPCore/IPCores02/LatticeMico32.aspx) into the repo? 

[From wikipedia](https://en.wikipedia.org/wiki/LatticeMico32);
> LatticeMico32 is a 32-bit microprocessor soft core from Lattice Semiconductor optimized for field-programmable gate arrays (FPGAs). It uses a Harvard architecture, which means the instruction and data buses are separate. Bus arbitration logic can be used to combine the two buses, if desired.
> 
> LatticeMico32 is licensed under a free (IP) core license. This means that the Mico32 is not restricted to Lattice FPGAs, and can be legally used on any host architecture (FPGA, ASIC, or software emulation (e.g. QEMU)). It is possible to embed a LatticeMico32 core into Xilinx and Altera FPGAs, in addition to the Lattice parts the LatticeMico32 was developed for. AMD PowerTune is using LatticeMico32.[1]
> 
> Both the CPU core and the development toolchain are available in source-code form, allowing third parties to implement changes to the processor architecture.

If so, I'll send a pull request with it!

Thanks!

**Comment by sam-falvo** [comment]
I think as long as the soft-CPU in question represents a *family*, I think that's OK.  The repository has a directory for RISC-V, for instance.  Although that directory doesn't include enough information to be able to use my KCP53000 CPU design (a 64-bit RISC-V integer-only, machine-mode-only design), it does provide adequate information to be able to start programming it once you do instantiate it.

This leads to a good question concerning soft-CPUs then: at what point do we stop?  If I were to submit my KCP53000 processor design to this repo, would it go under RISC-V?  Or would it get a top-level directory all to its own?  I can think of several arguments in favor of both approaches.

(Footnote: I would never submit KCP53000, since it's not a "great CPU".  I use it for my own projects, and to my knowledge, it only has one other user outside of the Kestrel.  Although it can be treated a lot like a 64-bit Z80, it's had no up-take in the open hardware community.  Oh well.)

**Comment by mithro** [comment]
I think some good criteria are;
 * Does it have support in gcc or llvm? Upstream support is a stronger argument.
 * Does it have support in upstream QEMU and/or Linux? More support, the stronger the argument.
 * Is it used by multiple companies / open source groups? The more, the stronger argument.

In terms of "soft-CPU architectures" I think the following are possibly worth considering;
 * LM32 - Up till recently the only open CPU designed for FPGAs which currently has upstream gcc support. Still seems to fit FPGAs better then RISC-V but that may change in the future. No upstream Linux support but is found in QEMU.
 * or1k - The first attempt at what RISC-V succeeds in doing. Has Linux, QEMU and LLVM support all upstream. People are currently working on gcc upstream support.
 * MicroBlaze - The soft CPU most people end up using on Xilinx FPGAs. Decent gcc, qemu and Linux support.
 * Nios2 - The soft CPU most people end up using on Altera FPGAs. Decent gcc, qemu and Linux support.

Thoughts?

**Comment by larsbrinkhoff** [comment]
I don't have anything against soft-cpus.  I don't think it would be appropriate to add everyone's toy CPU simulator, but it hasn't been a problem so far.

My intent has been to have a single directory for each "family" (which is loosely defined, if at all).
